services:
  php:
    build:
      context: .
      dockerfile: containers/php/Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./containers/nginx/conf.d/:/etc/nginx/conf.d/
      - storage:/var/www/storage
    depends_on:
      - php

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "pokemons"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"

volumes:
  postgres_data:
  storage:
